### ISSUE TITLE
Error while starting windows client with cmd "npx electronmon ."

### ISSUE THREAD

**Issue by NandishNR** [ishantchauhan710/DeskViewer#1]
Hi,
I have used your project and able to run server in my local windows machine. Facing issue while running client.

Initially got an error **NODE_MODULE_VERSION 108. This version of Node.js requires NODE_MODULE_VERSION 113**. 

Since NODE_MODULE_VERSION 113 version is not available, installed NODE_MODULE_VERSION 115. After rebuild and start getting below error.  **build\Release\robotjs.node** package is available in node_modules

App threw an error during load
Error: The module '\\?\,,,,app\node_modules\robotjs\build\Release\robotjs.node' was compiled against a different Node.js version using
NODE_MODULE_VERSION 115. This version of Node.js requires NODE_MODULE_VERSION 113.

Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1259:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module._load (C:\Users\nandish.nr\AppData\Local\npm-cache\_npx\a9286e5dc762839a\node_modules\runtime-required\runtime-required.js:34:23)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\nandish.nr\source\repos\DeskViewer\app\node_modules\robotjs\index.js:1:15)

**Comment by ishantchauhan710** [comment]
I faced the same issue when I was working on this project. This issue comes
from the robotjs library and occurs because the build version of robotjs is
not compatible with the version of electronjs you are using.

To fix it, you need to rebuild robotjs library so that it gets compatible
with electron. To do this, Refer to the following ways:

Way 1:

npm rebuild robotjs --update-binary


Way 2:

Refer to: https://github.com/octalmage/robotjs/issues/466#issuecomment-590491327


Way 3:

Refer to: https://github.com/octalmage/robotjs/issues/646

**Comment by NandishNR** [comment]
CMD **npx electron-rebuild -f -t prod,optional,dev -w robotjs** solved the problem by rebuilding to match node.js version
