### ISSUE TITLE
Getting this error while starting the app. 

### ISSUE THREAD

**Issue by najuBhadarka** [ishantchauhan710/DeskViewer#3]
```
App threw an error during load
Error: \\?\D:\DeskViewer\app\node_modules\robotjs\build\Release\robotjs.node is not a valid Win32 application.
\\?\D:\DeskViewer\app\node_modules\robotjs\build\Release\robotjs.node
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\DeskViewer\app\node_modules\robotjs\index.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
D:\DeskViewer\app\node_modules\electron\dist\electron exited with signal SIGINT
```

**Comment by liyang51827** [comment]
Check your node.js version and the version dependencies with `robot.js`. Maybe you should rebuild the `robot.js` native module using `node-gyp`. Please refer to this original tutorial post below:
https://ishantchauhan.hashnode.dev/deskviewer-how-i-created-and-debugged-a-remote-desktop-application#heading-4-robotjs-node-version-build-error

**Comment by najuBhadarka** [comment]
This issue is resolved from my end and I have found the way to fix this issue.
